version: '3.9'
services:
  mysql-container:
    container_name: mysql-container
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ContentDigitalCalendar
    ports:
      - "3307:3306"
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
      - ./be/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - backend

  spring-boot-container:
    # image: khoaly/ideasy-calendar
    build:
      context: ./be
      dockerfile: Dockerfile 
    container_name: spring-boot-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATASOURCE_URL=jdbc:mysql://mysql-container:3306/ContentDigitalCalendar?serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DATABASE_PASSWORD=12345
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
    depends_on:      
      - mysql-container
    networks:
      - backend
    expose:
      - 8080

  nginx:
    image: nginx:1.25.5
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./fe/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - spring-boot-container
    networks:
      - backend

volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:

networks:
  backend:
    driver: bridge