spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/ContentDigitalCalendar}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:12345}
    driver-class-name: com.mysql.jdbc.Driver