version: '3.9'
services:
  mysql-container:
    container_name: mysql-container
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ContentDigitalCalendar
    ports:
      - "3307:3306"
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379" # Port mapping for Redis, you can change the host port as needed
    volumes:
      - ./redis-data:/data # Mount a volume for Redis data persistence
    networks:
      - backend

  spring-boot-container:
    container_name: spring-boot-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATASOURCE_URL=jdbc:mysql://mysql-container:3306/ContentDigitalCalendar?serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DATABASE_PASSWORD=12345
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
    networks:
      - backend

volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:

networks:
  backend:
    driver: bridge