name: neway creative be ci

on:
  push:
    branches: ["production"]
    paths:
      - "be/**"
      - ".github/workflows/neway-creative-be-ci.yaml"
  pull_request:
    branches: ["production"]
    paths:
      - "be/**"
      - ".github/workflows/neway-creative-be-ci.yaml"

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 17

      - name: Build the application
        run: |
          cd be
          mvn clean
          mvn -B package -P dev -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: be
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ideasy-calendar:latest
